server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    password : guest
    port: 5672
    username: guest
    exchange: registroExchange
    queue: registroQueue
    routingkey: registroQueue
    cachesize : 500